Establish html page and their css for start and event pages
andy-keene/sps-project-2022 pull request #3
Opened 2022-07-11 22:44 UTC by DPWXY

2022-07-12 23:28 UTC, MattWong-ca commented
We can change "After College / University" to "Graduated", and everything else I think you mentioned you'd add in our meeting, so looks good to me!

2022-07-15 22:04 UTC, dalshekerchi requested changes

2022-07-15 22:04 UTC, dalshekerchi commented on project/src/main/webapp/Event_Page.css
> +#content {
I think that the naming convention for html and css files are kebab case which means that this file would be event-page.css, I didn't know this either so I will need to change mine too

2022-07-15 22:04 UTC, dalshekerchi commented on project/src/main/webapp/Event_Page.css
> +}
I think it's good practice to add a newline at the end of each file

2022-07-15 22:04 UTC, dalshekerchi commented on project/src/main/webapp/Start_Page.html
> +                    <img src="..." class="card-img" alt="...">
https://clipart.world/wp-content/uploads/2020/08/calendar-and-clock-icon-transparent.png
this might be a nice image to add, just a suggestion if you find anything nicer go for it

2022-07-15 22:04 UTC, dalshekerchi commented on project/src/main/webapp/Start_Page.html
> +                    <p class="card-text">Find an event for you</p>
Maybe something like this here, it's a ticket for an event https://images.vexels.com/media/users/3/220739/isolated/preview/364a8081b080c3b1b1af9abb49ecf40e-classic-movie-tickets-flat-icon.png

2022-07-17 17:28 UTC, dalshekerchi approved these changes

2022-07-17 18:16 UTC, merged